### ISSUE TITLE
Downloadlinks tun nicht

### ISSUE THREAD

**Issue by hswlab** [bmmlms/streamwriter#1]
Hi Alex, auf deiner Website tun die Downloadlinks auf der rechten Seite nicht. Man kommt auf eine 404 Seite, wenn der Link angeklickt wird. Die Links auf der linken Seite funktionieren aber. Man kennt ja die Anwender, wenn etwas beim ersten Klick nicht tut, wird es gleich aufgegeben ;-)

![image](https://github.com/bmmlms/streamwriter/assets/12501993/7f89b08d-6a7f-4fba-bb01-3d923d3b3deb)

Hab gesehen, dass du sogar noch diese Jahr Updates für den StreamWriter gemacht hast. Danke, dass du noch ab und zu ein Auge auf deine älteren Projekte hast. Dein Tool benutze ich noch immer lieber, als die Audials Alternative. Es ist klein, schnell, übersichtlich, nach einem Windows-Reset ist es samt Lieblingssendern schnell eingerichtet und man muss nicht irgendwelche Accounts dafür anlegen. Ich hoffe das bleibt uns noch lange erhalten :)

**Comment by bmmlms** [comment]
Hey, danke für das Issue, habe ich eben behoben :)
Schön, dass dir die Software gefällt - ich habe nicht mehr so viel Zeit mich drum zu kümmern aber versuche das am Leben zu halten und wollte demnächst auch mal wieder ein richtiges Release rausbringen. Dauert hoffentlich nicht mehr lange...
